fix: treat arrow functions in property declarations and assignments as non-anonymous
brandhaug/add-function-return-types pull request #1
Opened 2024-11-08 14:40 UTC by jwbth

Hello. As I [said](https://www.reddit.com/r/typescript/comments/itxos7/comment/lvy2tcw/) in a comment on Reddit, this repo is a real treasure!

An hour ago, you've also implemented the exact feature I was about to request – ignoring anonymous functions.

There is a problem though: it correctly handles variable declarations but overlooks property declarations like this:
```ts
class Class {
    arrowClassProp = () => {
        return 456;
    }
}
```
and property assignments like this:
```ts
const object = {
    arrowObjectProp: () => {
        return 456;
    }
}
```

These are sometimes used to simplify adding and removing event listeners, because they automatically capture `this` and provide a stable reference to uninstall, e.g. see [Google style guide](https://google.github.io/styleguide/tsguide.html#event-handlers).

`--ignore-anonymous-functions` should not ignore them.

This PR solves this to the extent that I could figure out `ts-morph`'s API. I added tests as well.

2024-11-08 20:40 UTC, jwbth commented
I just realized that apart from these two, there are also cases with simple assignment:
```ts
let variable;
variable = () => {
    return 456;
};
```
```ts
const object2 = {};
object2.arrowObject2Prop = () => {
    return 456;
};
```
I'm less sure how to handle this correctly, but tried my best.

2024-11-12 11:36 UTC, brandhaug requested changes
Thank you for your contribution! Can you just manually increment the patch version in package.json as I have no automation on this yet?

2024-11-14 13:52 UTC, brandhaug commented
Can you rebase your branch, please?

2024-11-14 15:28 UTC, jwbth commented
Done.

2024-11-19 07:58 UTC, brandhaug approved these changes
Thank you!

2024-11-19 07:58 UTC, merged